name: Test it

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build default
        run: cargo build

      - name: Build full
        run: cargo build --features full

      - name: Build service-bus
        run: cargo build --features service-bus

      - name: Build no-sql
        run: cargo build --features no-sql